/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonEmptyView: typeof import('./../../packages/ui/src/components/common/EmptyView.vue')['default']
    CommonLeftMenu: typeof import('./../../packages/ui/src/components/common/LeftMenu.vue')['default']
    CommonMainView: typeof import('./../../packages/ui/src/components/common/MainView.vue')['default']
    CommonSplitView: typeof import('./../../packages/ui/src/components/common/SplitView.vue')['default']
    ConnectionsDetailsView: typeof import('./../../packages/ui/src/components/connections/DetailsView.vue')['default']
    ConnectionsListView: typeof import('./../../packages/ui/src/components/connections/ListView.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElMain: typeof import('element-plus/es')['ElMain']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
