/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutFooter: typeof import('./../../packages/ui/src/components/about/Footer.vue')['default']
    AboutInfo: typeof import('./../../packages/ui/src/components/about/Info.vue')['default']
    AboutView: typeof import('./../../packages/ui/src/components/about/View.vue')['default']
    CommonEmptyView: typeof import('./../../packages/ui/src/components/common/EmptyView.vue')['default']
    CommonLeftMenu: typeof import('./../../packages/ui/src/components/common/LeftMenu.vue')['default']
    CommonMainView: typeof import('./../../packages/ui/src/components/common/MainView.vue')['default']
    CommonSplitView: typeof import('./../../packages/ui/src/components/common/SplitView.vue')['default']
    ConnectionsDetailsView: typeof import('./../../packages/ui/src/components/connections/DetailsView.vue')['default']
    ConnectionsListView: typeof import('./../../packages/ui/src/components/connections/ListView.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascaderPanel: typeof import('element-plus/es')['ElCascaderPanel']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIconDelete: typeof import('@element-plus/icons-vue')['Delete']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconPrinter: typeof import('@element-plus/icons-vue')['Printer']
    ElIconRight: typeof import('@element-plus/icons-vue')['Right']
    ElIconUpload: typeof import('@element-plus/icons-vue')['Upload']
    ElIconWarning: typeof import('@element-plus/icons-vue')['Warning']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelpView: typeof import('./../../packages/ui/src/components/HelpView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../../packages/ui/src/components/SettingsView.vue')['default']
  }
}
