name: units test cli

on:
  pull_request:
    paths:
      - 'cli/**'
  release:
    types:
      - published

jobs:
  cli_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'cli/.nvmrc'

      - name: Install dependencies and run tests
        run: |
          cd cli
          yarn
          yarn build
          yarn test:coverage

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
